name: Docker Build & Publish to GHCR

on:
  push:
    branches:
      - main

jobs:
  docker-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate with GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: |
          owner_lc=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker build \
            -t ghcr.io/$owner_lc/devops:latest \
            -t ghcr.io/$owner_lc/devops:${{ github.sha }} \
            --label "org.opencontainers.image.source=${{ github.repository }}" \
            .

      - name: Push Docker Images
        run: |
          owner_lc=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker push ghcr.io/$owner_lc/devops:latest
          docker push ghcr.io/$owner_lc/devops:${{ github.sha }}

